name: flutter_vk_app
description: A new VK Messanger

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_view: ^0.0.6
  cupertino_icons: ^0.1.3
  ant_icons: ^1.0.0
  json_serializable: ^3.4.0
  build_runner: ^1.10.2
  json_annotation: ^3.0.1
  flutter_group_sliver: ^0.0.2
  intl: ^0.16.1
  flutter_staggered_grid_view: ^0.3.2
  photo_view: ^0.10.0
  flare_flutter: ^2.0.6
  transparent_image: ^1.0.0
  auto_animated: ^2.1.0
  http: ^0.12.2
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-Black.ttf
  assets:
    - assets/